### ISSUE TITLE
Write to a new GTFS file

### ISSUE THREAD

**Issue by AimanKhan1997** [mrcagney/gtfs_kit#11]
Hi,

I was wondering if there is a way to create a new GTFS file. For example, I have the GTFS file that I want to edit to only focus on specific bus lines. Does feed has a write function or something similar to that to edit the dataset from the GTFS file and create a new file with the only the desired bus lines.

Thank you for time and consideration.

Regards,
Mohd Aiman

**Comment by araichev** [comment]
Yes: ``feed.write``. See the [docs](https://mrcagney.github.io/gtfs_kit_docs/).
