### ISSUE TITLE
Add filter to get num_trips on a specific period

### ISSUE THREAD

**Issue by ludovic-legros-ecov** [mrcagney/gtfs_kit#12]
Hi,

It would be interesting to filter num_trips so that it gives the number of trips on a specific period of time (it'd like to get the number of trains during peak hours for example using headway_start and headway_end parameters):

https://github.com/mrcagney/gtfs_kit/blob/d785cc422194fad5fb425eb52aff13af1b34d435/gtfs_kit/routes.py#L112-L119

Thanks !

**Comment by araichev** [comment]
You can do this with `compute_route_time_series`.
