### ISSUE TITLE
shapes_to_geojson - IllegalArgumentException: point array must contain 0 or >1 elements

### ISSUE THREAD

**Issue by ruipoliveira** [mrcagney/gtfs_kit#13]
I encountered an IllegalArgumentException with the message 'Point array must contain 0 or >1 elements' for all my shape_ids when using `gtfs-kit==8.1.0`. However, the same code works fine with `gtfs-kit==6.1.1`.

```
shape_ids = feed.shapes.shape_id.unique()[:2]
collection = gks.shapes_to_geojson(feed, shape_ids)
```

**Comment by araichev** [comment]
Thanks for the report @ruipoliveira . Can you attach a minimal reproducible example that triggers the message?

**Comment by ruipoliveira** [comment]
Hi @araichev. The issue arises only for shapes containing a single point. For all other shapes, the following error is consistently returned: `IllegalArgumentException: point array must contain 0 or more than 1 elements.`.

Here is the code and GTFS data I’m currently using. Thanks for your time.

[gtfs.zip](https://github.com/user-attachments/files/17505530/gtfs.zip)


```
from pathlib import Path
import shapely
import gtfs_kit
from gtfs_kit import shapes as gks

path = Path(f"gtfs.zip")
feed = gtfs_kit.read_feed(path, dist_units="km")

shape_ids = feed.shapes.shape_id.unique()

for shape_id in shape_ids: 
    print(shape_id)
    try:
        collection = gks.shapes_to_geojson(feed, [shape_id])
        print(collection)
    except shapely.errors.GEOSException as e:
        print(f"Exception: {e}" )
```

**Comment by araichev** [comment]
Thanks for the example feed @ruipoliveira . 
Fixed now to handle shapes that comprise a single point in release 8.1.1. 

By the way, you don't have to import `gtfs_kit` modules separately to use the functions inside. For example, you can do 

```
import gtfs_kit as gk

feed = gk.read_feed(path, dist_units="km")
gk.shapes_to_geojson(feed)
# Or more easily:
feed.shapes_to_geojson()
```
