### ISSUE TITLE
platform_code on stops.txt

### ISSUE THREAD

**Issue by ruipoliveira** [mrcagney/gtfs_kit#14]
https://gtfs.org/documentation/schedule/reference/#stopstxt

I checked that the field **platform_code** is optional on stops.txt, but not present on gtfs-kit validator.

Thanks

**Comment by araichev** [comment]
Good point @ruipoliveira . I'm thinking of retiring the validation module, though, in favor of the [canonical GTFS validator](https://gtfs-validator.mobilitydata.org/) (written in Java), so i'm going to put this issue on the back burner for now.

**Comment by araichev** [comment]
Validation removed now in release 10.0.0 and issue dissolved :)
