### ISSUE TITLE
"geometrize_stops" and "sort values"

### ISSUE THREAD

**Issue by kyletitlowdot** [mrcagney/gtfs_kit#20]
When trying to use the "geometrize_stops" or "geometrize_routes" functions to build a stop and route geodataframe from an ingested GTFS file (all other files appear valid, including the stops and routes table), I get the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[9], line 1
----> 1 test.geometrize_shapes()

File ~\AppData\Local\anaconda3\envs\icba\Lib\site-packages\gtfs_kit\shapes.py:89, in geometrize_shapes(shapes, use_utm)
     84         d["geometry"] = sg.Point(coords)
     86     return pd.Series(d)
     88 g = (
---> 89     shapes.sort_values(["shape_id", "shape_pt_sequence"])
     90     .groupby("shape_id", sort=False)
     91     .apply(my_agg, include_groups=False)
     92     .reset_index()
     93     .pipe(gpd.GeoDataFrame)
     94     .set_crs(cs.WGS84)
     95 )
     97 if use_utm:
     98     g = g.to_crs(g.estimate_utm_crs())

**AttributeError: 'Feed' object has no attribute 'sort_values'**

**Comment by araichev** [comment]
Is `test` a Feed instance? If so, then you want to do `test.get_shapes(as_gdf=True)`. The function `geometrize_shapes` applies to shapes DataFrames, as described in the docs and docstrings.
