### ISSUE TITLE
Memory footprint

### ISSUE THREAD

**Issue by GaspardMerten** [mrcagney/gtfs_kit#5]
I wondered if you had an idea about why the first access to trips (so loading trips in memory), eats more than 1.5 GB for a relatively standard gtfs?

(also, thank you for this amazing package)

**Comment by araichev** [comment]
Hello @GaspardMerten , thanks for your feedback.
When you read a GTFS feed with GTFS Kit, all GTFS tables get stored as DataFrames in memory.
That's it for the memory footprint.
How big it is depends on your feed size and Pandas.

**Comment by GaspardMerten** [comment]
@araichev, do you think it would be possible to filter trips based on day without loading the entire GTFS file at once?

**Comment by araichev** [comment]
Hi @GaspardMerten , GTFS Kit can't do that, but it can create a smaller feed for you via the method [`restrict_to_routes`](https://mrcagney.github.io/gtfs_kit_docs/index.html#gtfs_kit.miscellany.restrict_to_routes), which you can then load into memory.
Does that do what you want?

Alternatively, [Patridge](https://github.com/remix/partridge) might do what you want, but i haven't tried it.

**Comment by GaspardMerten** [comment]
Thank you very much!

Have a good day 😀
