### ISSUE TITLE
potentially wrong handling of GTFS Time values

### ISSUE THREAD

**Issue by derhuerst** [mrcagney/gtfs_kit#8]
[GTFS Time is not defined relative to midnight, but relative to noon - 12h](https://gist.github.com/derhuerst/574edc94981a21ef0ce90713f1cff7f6). While that makes "writing" GTFS feeds easier, it makes processing a lot harder.

**Expected functionality**

As explained in my [note about GTFS Time values](https://gist.github.com/derhuerst/574edc94981a21ef0ce90713f1cff7f6), with the `Europe/Berlin` time zone (+1h standard time to +2 DST shift occurs at `2021-03-28T02:00+01:00`), I expect

- the `departure_time` of `00:30` of a trip running on `2021-03-28` to happen at `1616884200`/`2021-03-28T00:30+02:00`, *not* at `1616887800`/`2021-03-28T00:30+01:00`;
- the `departure_time` of `06:30` of a trip running on `2021-03-28` to happen at `1616905800`/`2021-03-28T06:30+02:00`, *not* at `1616909400`/`2021-03-28T06:30+01:00`.

**Describe the bug**

I'm very inexperienced with R and not that familiar with this code base, but **it *seems* that gtfs_kit is affected by this problem on those days that the DST <-> standard time switch occurs on**.

I'm not sure how that actually manifests in gtfs_kit's output, but I assume that wrong delays will be calculated, or that realtime data can't be matched against static data.

I tried to find some places in the code base:

- https://github.com/mrcagney/gtfs_kit/blob/8ed76da2c20d163090829f405c7771f7faa8773b/gtfs_kit/trips.py#L86-L103
- https://github.com/mrcagney/gtfs_kit/blob/8ed76da2c20d163090829f405c7771f7faa8773b/gtfs_kit/trips.py#L211-L225
- https://github.com/mrcagney/gtfs_kit/blob/8ed76da2c20d163090829f405c7771f7faa8773b/gtfs_kit/trips.py#L248
-

**Comment by araichev** [comment]
Thanks for pointing this out @derhuerst .
My reply is the same as https://github.com/r-transit/tidytransit/issues/175#issuecomment-979323318 .
That said i will clearly document this potential issue in the README.
